"""Sphinx configuration for the country libraries.

This is deliberately close to the configuration these documents will land in.  lifelib's
``doc/source/conf.py`` already loads ``myst_parser``, ``autodoc``, ``autosummary`` and
``napoleon``, already sets ``autodoc_member_order = 'bysource'``, and already puts the
directory holding the libraries on ``sys.path``.  Everything here mirrors that; there is no
configuration specific to this doc set at all.

**The pages are here; the prose is in the library.**  Each page under ``libraries/uslib/``
is a one-line ``{include}`` of the corresponding library document, and the page tree mirrors
the library tree so that the authored relative links keep resolving.  Nothing is copied and
nothing is generated at build time, so the documents have exactly one home.

That also lets the autodoc pages -- ``<Model>.rst`` and one ``<Space>.rst`` per Space,
following ``annuallife/TradLife_A.rst`` -- live only here.  They are Sphinx plumbing rather
than library content, and a ``lifelib.create()`` copy is better without them.

Both are regenerated by ``python tools/gen_scaffolding.py uslib``.

The only structural difference from lifelib is where the libraries live.  Here they are
top-level directories (``uslib/``, and ``uklib/`` when it exists); in lifelib they are under
``lifelib/libraries/``.  That is one path in :data:`LIBRARY_ROOT`.

Build it::

    cd doc && make html

or, to fail on anything that would render wrong::

    python tools/doccheck.py
"""
import sys
from pathlib import Path


here = Path(__file__).resolve().parent
REPO = here.parents[1]

# Where the country libraries live.  In lifelib this is `lifelib/libraries`.
LIBRARY_ROOT = REPO

# autodoc imports the models to read their cells docstrings, so the library must be
# importable under the name its documents use: `uslib.products.term_life.Term_US_A`.
# lifelib does the same thing one level down, which is why the product slugs are
# underscored -- every component of that path has to be a Python identifier.
sys.path.insert(0, str(LIBRARY_ROOT))


# -- Project ---------------------------------------------------------------------------

project = "lifelib-products"
copyright = "2026, Fumito Hamamura"
author = "Fumito Hamamura"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx_design",
    "myst_parser",
]

# myst_parser registers `.md` itself; this is the RST half, as in lifelib.
source_suffix = ".rst"
master_doc = "index"

# _research/ ships with the library -- it is the evidence behind the documents -- but it is
# not rendered: it carries its own deliberately independent [S#] numbering, and a second,
# conflicting S1 in front of a reader is worse than not publishing it (D6).  With the page
# tree written out rather than mirrored, that is simply a matter of giving it no pages.
exclude_patterns = ["_build"]

# Deliberately empty, matching lifelib.  Enabling `dollarmath` would read the corpus's
# currency -- $100,000, $1,000 -- as maths (C12).
myst_enable_extensions = []

add_module_names = False
autodoc_member_order = "bysource"
autosummary_generate = True

# Off by default; `tools/doccheck.py` turns it on with -n.  It must be on for any build
# that claims the cross-references work, because Sphinx does not warn about an unresolved
# :func:/:mod: role -- it drops the role and renders plain text (D9).
nitpicky = False


# -- HTML ------------------------------------------------------------------------------

html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
html_title = "lifelib-products"
html_last_updated_fmt = "%b %d, %Y"
html_theme_options = {
    "header_links_before_dropdown": 6,
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/fumitoh/lifelib-products",
            "icon": "fab fa-github-square",
        }
    ],
}
